package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import model.IbCustomer;
import model.IbCustomerRelation;
import model.IbCustomerType;
import model.IbInsurance;
import model.IbMasterValue;
import model.MasterTypes;
import model.TableInfo;
import model.TableInfoRelation;
import util.InsureCompleteVO;

import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;

import com.github.daytron.simpledialogfx.data.DialogResponse;
import com.github.daytron.simpledialogfx.dialog.Dialog;
import com.github.daytron.simpledialogfx.dialog.DialogType;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;

public class InsureOverviewController {

	private InsureCompleteVO icVO = null;
	@FXML
	private ComboBox cbCompania;

	public ComboBox getcbCompania() {
		return cbCompania;
	}

	@FXML
	private TextField tvPoliza;
	@FXML
	private ComboBox cbFormaPago;

	public ComboBox getcbFormaPago() {
		return cbFormaPago;
	}

	@FXML
	private DatePicker dpFechaInicio;
	@FXML
	private DatePicker dpFechaFin;
	@FXML
	private TextField tvPrimaNeta;
	@FXML
	private ComboBox cbDuracion;

	public ComboBox getcbDuracion() {
		return cbDuracion;
	}

	@FXML
	private Label lbCliente;

	// Event Listener on Button.onAction
	@FXML
	public void handleAnadirFormaPago(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button.onAction
	@FXML
	public void handleAnadirCompania(ActionEvent event) {
		Parent root;
		FXMLLoader loader = new FXMLLoader(getClass().getResource("/views/MasterValuesOverview.fxml"));

		try {
			root = (Parent) loader.load();
			Stage stage = new Stage();
			stage.setTitle("Información maestro de valores.");
			MasterValuesOverviewController controller = loader.<MasterValuesOverviewController> getController();
			stage.setScene(new Scene(root, 750, 480));
			stage.setScene(stage.getScene());
			controller.initData(MasterTypes.TYPE_COMPANIA);
			stage.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	@FXML
	public void handleSiguiente(ActionEvent event) {
		String duracion = cbDuracion.getSelectionModel().getSelectedItem().toString();
		LocalDate dateInicio = dpFechaInicio.getValue();
		LocalDate dateInicioAux = dpFechaInicio.getValue();
		LocalDate dateFin = dpFechaFin.getValue();
		LocalDate dateImpuestaFin;
		boolean aviso = false;
		switch (duracion) {
		case "ANUAL":
			dateImpuestaFin = dateInicio.plusYears(1);
			if (!dateImpuestaFin.equals(dateFin)) {
				aviso = true;
			}
			break;
		case "SEMESTRAL":
			dateImpuestaFin = dateInicio.plusMonths(6);
			if (!dateImpuestaFin.equals(dateFin)) {
				aviso = true;
			}
			break;
		case "TRIMESTRAL":
			dateImpuestaFin = dateInicio.plusMonths(3);
			if (!dateImpuestaFin.equals(dateFin)) {
				aviso = true;
			}
			break;

		default:

			break;
		}
		boolean showWindowBank = true;
		if (dateInicioAux.isBefore(dateFin)) {
			if (aviso) {
				Dialog dialog = new Dialog(DialogType.CONFIRMATION, "INFORMACIÓN",
						"¿Estás seguro qué desear seguir, ya que el tipo de duración "
								+ cbDuracion.getSelectionModel().getSelectedItem()
								+ " difiere con las fechas establecidas en fecha inicio: " + dpFechaInicio.getValue()
								+ " y fecha fin: " + dpFechaFin.getValue() + "?");
				dialog.showAndWait();
				if (dialog.getResponse() == DialogResponse.YES) {
					showWindowBank = true;
				} else {
					showWindowBank = false;
				}

			}
		} else {
			Dialog dialog = new Dialog(DialogType.INFORMATION, "INFORMACIÓN", "La fecha fin: " + dpFechaFin.getValue()
					+ " no puede ser anterior a la fecha inicio: " + dpFechaInicio.getValue());

			dialog.showAndWait();
			showWindowBank = false;
		}
		if (showWindowBank) {
			if (!tvPoliza.getText().isEmpty() && cbCompania.getSelectionModel().getSelectedItem() != null
					&& cbDuracion.getSelectionModel().getSelectedItem() != null
					&& cbFormaPago.getSelectionModel().getSelectedItem() != null) {

				Parent root;
				FXMLLoader loader = new FXMLLoader(getClass().getResource("/views/BankAccountOverview.fxml"));

				try {
					root = (Parent) loader.load();
					Stage stage = new Stage();

					stage.setTitle("Datos Cuenta Bancaria.");
					stage.setScene(new Scene(root, 550, 370));
					stage.setScene(stage.getScene());
					BankAccountOverviewController controller = (BankAccountOverviewController) loader.getController();
					IbInsurance datosSeguro = new IbInsurance();
					datosSeguro.setCompania(cbCompania.getSelectionModel().getSelectedItem().toString());
					datosSeguro.setDuracion(duracion);
					datosSeguro.setFormaPago(cbFormaPago.getSelectionModel().getSelectedItem().toString());
					// datosSeguro.setEstado(estado);
					Date utilDateInicio = Date
							.from(dpFechaInicio.getValue().atStartOfDay(ZoneId.systemDefault()).toInstant());
					Date utilDateFin = Date
							.from(dpFechaFin.getValue().atStartOfDay(ZoneId.systemDefault()).toInstant());
					datosSeguro.setFechaEntradaVigor(utilDateInicio);
					datosSeguro.setFechaInicio(utilDateInicio);
					datosSeguro.setFechaFin(utilDateFin);
					icVO.setDatosSeguro(datosSeguro);
					controller.initData(icVO);
					stage.show();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
	}

	@FXML
	public void handleDuracionCB(ActionEvent event) {
		LocalDate ldFechaInicio = dpFechaInicio.getValue();
		String duracion = cbDuracion.getSelectionModel().getSelectedItem().toString();
		if (!duracion.isEmpty()) {
			LocalDate date = date = dpFechaInicio.getValue();
			switch (duracion) {
			case "ANUAL":
				dpFechaFin.setValue(date.plusYears(1));
				break;
			case "SEMESTRAL":
				dpFechaFin.setValue(date.plusMonths(6));
				break;
			case "TRIMESTRAL":
				dpFechaFin.setValue(date.plusMonths(3));
				break;

			default:
				dpFechaFin.setValue(date.plusYears(1));
				break;
			}
		}

	}

	public void initData(InsureCompleteVO icVO) {
		Iterator itr = icVO.getDatosClienteRelation().iterator();
		String dni = "";
		while (itr.hasNext()) {
			TableInfoRelation element = (TableInfoRelation) itr.next();
			if (element.getTipo().equals("TITULAR")) {
				lbCliente.setText(element.getNombre() + " " + element.getApellidos());
				dni = element.getDni();
				icVO.setNombreCompletoTitular(lbCliente.getText());
				icVO.setDniTitular(dni);
			}
		}

		EntityManagerFactory emf;
		EntityManager em;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();
		EntityTransaction tx = em.getTransaction();
		TypedQuery<IbMasterValue> query = em.createNamedQuery("IbMasterValue.findByType", IbMasterValue.class);
		query.setParameter("type", "INFPA00");
		List<IbMasterValue> listFormaPago = query.getResultList();
		ObservableList<IbMasterValue> listaObservableFormaPago = FXCollections.observableArrayList(listFormaPago);
		getcbFormaPago().setItems(listaObservableFormaPago);

		TypedQuery<IbMasterValue> queryDuracion = em.createNamedQuery("IbMasterValue.findByType", IbMasterValue.class);
		queryDuracion.setParameter("type", "INDUR00");
		List<IbMasterValue> listDuracion = queryDuracion.getResultList();
		ObservableList<IbMasterValue> listaObsevableDuracion = FXCollections.observableArrayList(listDuracion);
		getcbDuracion().setItems(listaObsevableDuracion);

		TypedQuery<IbMasterValue> queryCompania = em.createNamedQuery("IbMasterValue.findByType", IbMasterValue.class);
		queryCompania.setParameter("type", "INTCS00");
		List<IbMasterValue> listCompania = queryCompania.getResultList();
		ObservableList<IbMasterValue> listaObsevableCompania = FXCollections.observableArrayList(listCompania);
		getcbCompania().setItems(listaObsevableCompania);

		TypedQuery<IbCustomer> queryCliente = em.createNamedQuery("IbCustomer.findDNI", IbCustomer.class);
		queryCliente.setParameter("dni", dni);
		List<IbCustomer> listCliente = queryCliente.getResultList();
		// TODO generar error de que si no existe cliente falle
		/*
		 * catch alerta de error
		 */
		icVO.setDatosCliente(listCliente.get(0));
		Date input = new Date();
		LocalDate date = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		dpFechaInicio.setValue(date);

		dpFechaFin.setValue(date.plusYears(1));

		this.icVO =icVO;
	}
}
