package controller;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;

import com.github.daytron.simpledialogfx.data.DialogResponse;
import com.github.daytron.simpledialogfx.dialog.Dialog;
import com.github.daytron.simpledialogfx.dialog.DialogType;

import algorit.algoNumber;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.CheckBox;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TableCell;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Modality;
import javafx.util.Callback;
import model.IbCuotesInsure;
import model.IbCuotesTime;
import model.IbCustomer;
import model.IbInsurance;
import model.IbMasterValue;
import model.MasterTypes;
import util.CalculateCuotes;
import util.DateUtil;
import util.masterValueUtil;

public class InsureCuotesMenuOverviewController {
	IbInsurance seguro;
	IbCustomer cliente;
	@FXML
	private Button btnAnadirDuracion;
	@FXML
	private ComboBox cbFormaPago;

	public ComboBox getcbFormaPago() {
		return cbFormaPago;
	}

	@FXML
	private DatePicker dpFechaInicio;
	@FXML
	private DatePicker dpFechaFin;
	@FXML
	private TextField tvPrimaNeta;

	public TextField gettvPrimaNeta() {
		return tvPrimaNeta;
	}

	@FXML
	private ComboBox cbDuracion;

	public ComboBox getcbDuracion() {
		return cbDuracion;
	}

	@FXML
	private Label lbCliente;

	public Label getlbCliente() {
		return lbCliente;
	}

	@FXML
	private DatePicker dpFechaEntradaVigor;
	@FXML
	private Label lbPoliza;

	public Label getlbPoliza() {
		return lbPoliza;
	}

	@FXML
	private Label lbCompania;

	public Label getlbCompania() {
		return lbCompania;
	}

	@FXML
	private TableView<IbCuotesInsure> tbCuotes;
	@FXML
	private TableColumn<IbCuotesInsure, String> ColumnNumCuota;
	@FXML
	private TableColumn<IbCuotesInsure, String> ColumnFechaPagoCuota;
	@FXML
	private TableColumn<IbCuotesInsure, Byte> ColumnPagado;
	@FXML
	private TableColumn<IbCuotesInsure, String> ColumnFechaPago;
	@FXML
	private TableColumn<IbCuotesInsure, Double> ColumnTotal;
	@FXML
	private Button btnAnadirDuracion1;
	@FXML
	private DatePicker dpFechaPagoCuota;
	@FXML
	private DatePicker dpFechaPago;
	@FXML
	private TextField tfTotalCuota;
	@FXML
	private Button btModificar;
	@FXML
	private Label lbCuota;
	@FXML
	private CheckBox cbPagado;

	// Event Listener on ComboBox[#cbFormaPago].onAction
	@FXML
	public void handleFormaPagoCB(ActionEvent event) {
		if (comprobarComboBoxes()) {
			String formaPago = cbFormaPago.getSelectionModel().getSelectedItem().toString();
			String duracion = cbDuracion.getSelectionModel().getSelectedItem().toString();
			IbCuotesTime ict = CalculateCuotes.getNumberCuotes(duracion, formaPago);
			int numMesesXcuota = 0;
			numMesesXcuota = ict.getIntervaloMeses() * ict.getNumeroCuotas();
			LocalDate date = dpFechaInicio.getValue();
			if (!formaPago.isEmpty()) {

				date = date.plusMonths(numMesesXcuota);

				dpFechaFin.setValue(date);
			}

			tbCuotes.getItems().clear();
			addRows(tbCuotes, ict, dpFechaInicio.getValue());
		}
	}

	@FXML
	public void handleDuracionCB(ActionEvent event) {
		if (comprobarComboBoxes()) {
			String formaPago = cbFormaPago.getSelectionModel().getSelectedItem().toString();
			String duracion = cbDuracion.getSelectionModel().getSelectedItem().toString();
			IbCuotesTime ict = CalculateCuotes.getNumberCuotes(duracion, formaPago);
			int numMesesXcuota = 0;
			numMesesXcuota = ict.getIntervaloMeses() * ict.getNumeroCuotas();
			LocalDate date = dpFechaInicio.getValue();
			if (!formaPago.isEmpty()) {

				date = date.plusMonths(numMesesXcuota);

				dpFechaFin.setValue(date);
			}

			tbCuotes.getItems().clear();
			addRows(tbCuotes, ict, dpFechaInicio.getValue());
		}
	}

	// Event Listener on Button[#btnAnadirDuracion1].onAction
	@FXML
	public void handleAnadirFormaPago(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#btModificar].onAction
	@FXML
	public void handleModificarCuota(ActionEvent event) {
		IbCuotesInsure selectedCuote = tbCuotes.getSelectionModel().getSelectedItem();
		if (DateUtil.isNumeric(tfTotalCuota.getText())) {
			List<IbCuotesInsure> list = new ArrayList<IbCuotesInsure>();

			ObservableList<IbCuotesInsure> obsAux = FXCollections.observableList(list);
			selectedCuote.setFechaOficialPago(DateUtil.LocalDateToDate(dpFechaPagoCuota.getValue()));
			selectedCuote.setFechaPagoCuota(DateUtil.LocalDateToDate(dpFechaPago.getValue()));
			selectedCuote.setTotalCuota(Double.parseDouble(tfTotalCuota.getText()));
			byte selected = 0;
			if (cbPagado.isSelected()) {
				selected = 1;
			}
			selectedCuote.setPagado(selected);
			ObservableList<IbCuotesInsure> obs = tbCuotes.getItems();
			for (int i = 0; i < obs.size(); i++) {
				IbCuotesInsure cuote = obs.get(i);
				if (cuote.getNumOrden() == selectedCuote.getNumOrden()) {
					cuote = selectedCuote;
				}
				obsAux.add(cuote);
			}
			tbCuotes.getItems().clear();
			tbCuotes.setItems(obsAux);
			tbCuotes.refresh();
		}

	}

	public void initData(IbInsurance seguro, IbCustomer cliente, boolean mismaVentana) {
		this.cliente = cliente;
		this.seguro = seguro;
		getlbCliente().setText(cliente.getNombre() + " " + cliente.getApellidos());
		getlbCompania().setText(seguro.getCompania());
		getlbPoliza().setText(seguro.getNumeroPoliza());
		String formaPago = masterValueUtil.getMasterFindDescriptionByValor(seguro.getFormaPago());

		String duracion = masterValueUtil.getMasterFindDescriptionByValor(seguro.getDuracion());

		EntityManagerFactory emf;
		EntityManager em;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();
		EntityTransaction tx = em.getTransaction();
		TypedQuery<String> query = em.createNamedQuery("IbMasterValue.findByType", String.class);
		query.setParameter("type", MasterTypes.TYPE_FORMA_PAGO);
		List<String> listFormaPago = query.getResultList();
		ObservableList<String> listaObservableFormaPago = FXCollections.observableArrayList(listFormaPago);
		getcbFormaPago().setItems(listaObservableFormaPago);
		getcbFormaPago().setValue(formaPago);

		TypedQuery<String> queryDuracion = em.createNamedQuery("IbMasterValue.findByType", String.class);
		queryDuracion.setParameter("type", MasterTypes.TYPE_DURACION);
		List<String> listDuracion = queryDuracion.getResultList();
		ObservableList<String> listaObsevableDuracion = FXCollections.observableArrayList(listDuracion);
		getcbDuracion().setItems(listaObsevableDuracion);
		getcbDuracion().setValue(duracion);
		gettvPrimaNeta().setText(String.valueOf(seguro.getPrimaNeta()));

		Date input = seguro.getFechaInicio();
		LocalDate lDate = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		dpFechaInicio.setValue(lDate);

		input = seguro.getFechaFin();
		lDate = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		dpFechaFin.setValue(lDate);

		input = seguro.getFechaEntradaVigor();
		lDate = input.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
		dpFechaEntradaVigor.setValue(lDate);

		IbCuotesTime ict = CalculateCuotes.getNumberCuotes(duracion, formaPago);
		tbCuotes.getItems().clear();

		addRowsIni(tbCuotes, ict, dpFechaInicio.getValue(), seguro);
		tbCuotes.getSelectionModel().selectedItemProperty()
				.addListener((observable, oldValue, newValue) -> showCuotesDetails(newValue));

	}

	private void addRowsIni(TableView<IbCuotesInsure> table, IbCuotesTime ict, LocalDate date, IbInsurance seguro) {
		ObservableList<IbCuotesInsure> allData = FXCollections.observableArrayList(seguro.getIbCuotesInsures());
		table.getColumns().clear();
		table.setItems(allData);

		ColumnNumCuota.setCellValueFactory(new PropertyValueFactory<IbCuotesInsure, String>("numOrden"));

		ColumnFechaPagoCuota.setCellValueFactory(
				new Callback<TableColumn.CellDataFeatures<IbCuotesInsure, String>, ObservableValue<String>>() {
					@Override
					public ObservableValue<String> call(TableColumn.CellDataFeatures<IbCuotesInsure, String> coutes) {
						SimpleStringProperty property = new SimpleStringProperty();
						DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
						property.setValue(dateFormat.format(coutes.getValue().getFechaOficialPago()));
						return property;
					}
				});
		ColumnPagado.setCellValueFactory(new PropertyValueFactory<IbCuotesInsure, Byte>("pagado"));

		ColumnFechaPago.setCellValueFactory(
				new Callback<TableColumn.CellDataFeatures<IbCuotesInsure, String>, ObservableValue<String>>() {
					@Override
					public ObservableValue<String> call(TableColumn.CellDataFeatures<IbCuotesInsure, String> coutes) {
						SimpleStringProperty property = new SimpleStringProperty();
						DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
						property.setValue(dateFormat.format(coutes.getValue().getFechaPagoCuota()));
						return property;
					}
				});
		ColumnTotal.setCellValueFactory(new PropertyValueFactory<IbCuotesInsure, Double>("totalCuota"));

		table.getColumns().addAll(ColumnNumCuota, ColumnFechaPagoCuota, ColumnPagado, ColumnFechaPago, ColumnTotal);

		ColumnPagado.setCellFactory(column -> {
			return new TableCell<IbCuotesInsure, Byte>() {
				@Override
				protected void updateItem(Byte item, boolean empty) {
					super.updateItem(item, empty);

					if (item != null || !empty) {
						CheckBox ck = new CheckBox();
						setAlignment(Pos.CENTER);
						boolean checked = false;
						if (item == 1) {
							checked = true;
						}
						ck.setSelected(checked);
						setDisable(true);
						setGraphic(ck);
					} else {

					}
				}
			};
		});

	}

	private void addRows(TableView table, IbCuotesTime ict, LocalDate date) {
		ObservableList<IbCuotesInsure> allData = table.getItems();
		IbCuotesInsure dataRow = new IbCuotesInsure();

		int numCuotas = ict.getNumeroCuotas();
		int meses = ict.getIntervaloMeses();
		int numMesesXcuota = 0;
		LocalDate lcAux;
		byte pagado = 0;
		if (null != tvPrimaNeta && !tvPrimaNeta.getText().isEmpty() && DateUtil.isNumeric(tvPrimaNeta.getText())) {

			double total = Double.parseDouble(tvPrimaNeta.getText());

			List<Double> listaTotalCuotas = algoNumber.getFirstTotal(total, numCuotas);

			table.getColumns().clear();
			for (int i = 0; i < numCuotas; i++) {
				dataRow = new IbCuotesInsure();
				numMesesXcuota = (i) * meses;
				lcAux = date.plusMonths(numMesesXcuota);
				Date fechaOficialPago = Date.from(lcAux.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());

				dataRow.setNumOrden(i + 1);
				dataRow.setFechaOficialPago(fechaOficialPago);
				dataRow.setPagado(pagado);
				dataRow.setFechaPagoCuota(fechaOficialPago);
				dataRow.setTotalCuota(listaTotalCuotas.get(i));
				allData.add(dataRow);
			}
			// CheckBox cbPagado = new CheckBox();
			ColumnNumCuota.setCellValueFactory(new PropertyValueFactory<IbCuotesInsure, String>("numOrden"));
			// ColumnFechaPagoCuota
			// .setCellValueFactory(new PropertyValueFactory<IbCuotesInsure,
			// String>("fechaOficialPago"));
			ColumnFechaPagoCuota.setCellValueFactory(
					new Callback<TableColumn.CellDataFeatures<IbCuotesInsure, String>, ObservableValue<String>>() {
						@Override
						public ObservableValue<String> call(
								TableColumn.CellDataFeatures<IbCuotesInsure, String> coutes) {
							SimpleStringProperty property = new SimpleStringProperty();
							DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
							property.setValue(dateFormat.format(coutes.getValue().getFechaOficialPago()));
							return property;
						}
					});
			// ColumnPagado.setSortable(false);
			ColumnPagado.setCellValueFactory(new PropertyValueFactory<IbCuotesInsure, Byte>("pagado"));

			// ColumnFechaPago.setCellValueFactory(new
			// PropertyValueFactory<IbCuotesInsure, Date>("fechaPagoCuota"));
			ColumnFechaPago.setCellValueFactory(
					new Callback<TableColumn.CellDataFeatures<IbCuotesInsure, String>, ObservableValue<String>>() {
						@Override
						public ObservableValue<String> call(
								TableColumn.CellDataFeatures<IbCuotesInsure, String> coutes) {
							SimpleStringProperty property = new SimpleStringProperty();
							DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
							property.setValue(dateFormat.format(coutes.getValue().getFechaPagoCuota()));
							return property;
						}
					});
			ColumnTotal.setCellValueFactory(new PropertyValueFactory<IbCuotesInsure, Double>("totalCuota"));

			table.getColumns().addAll(ColumnNumCuota, ColumnFechaPagoCuota, ColumnPagado, ColumnFechaPago, ColumnTotal);

			ColumnPagado.setCellFactory(column -> {
				return new TableCell<IbCuotesInsure, Byte>() {
					@Override
					protected void updateItem(Byte item, boolean empty) {
						super.updateItem(item, empty);

						if (item != null || !empty) {
							CheckBox ck = new CheckBox();
							setAlignment(Pos.CENTER);
							boolean checked = false;
							if (item == 1) {
								checked = true;
							}
							ck.setSelected(checked);
							setDisable(true);
							setGraphic(ck);
						} else {

						}
					}
				};
			});
		}
	}

	@FXML
	private void initialize() {

	}

	private IbCuotesInsure showCuotesDetails(IbCuotesInsure cuoteSelected) {
		// TODO Auto-generated method stub
		if (cuoteSelected != null) {
			// Fill the labels with info from the person object.
			lbCuota.setText(String.valueOf(cuoteSelected.getNumOrden()));
			dpFechaPago.setValue(DateUtil.dateToLocalDate(cuoteSelected.getFechaPagoCuota()));
			dpFechaPagoCuota.setValue(DateUtil.dateToLocalDate(cuoteSelected.getFechaOficialPago()));
			// cbPagado.setDisable(false);
			boolean selected = false;
			if (cuoteSelected.getPagado() == 1) {
				selected = true;
			}
			cbPagado.setSelected(selected);
			tfTotalCuota.setText(String.valueOf(cuoteSelected.getTotalCuota()));

		} else {
			// Person is null, remove all the text.
			lbCuota.setText("0");
			cbPagado.setSelected(false);
			tfTotalCuota.setText("");
			dpFechaPagoCuota.setValue(null);
			dpFechaPago.setValue(null);
		}
		return cuoteSelected;
	}

	@FXML
	public void handleAceptarCambios(ActionEvent event) {
		String messageInfo = "";
		String messageError = "";
		IbCuotesInsure ci = new IbCuotesInsure();
		IbInsurance insuOfficialCopy = new IbInsurance();
		LocalDate dateIniVigor = dpFechaEntradaVigor.getValue();
		LocalDate dateFinVigor = LocalDate.now(ZoneId.of(ZoneId.systemDefault().toString()));
		String duracion = cbDuracion.getSelectionModel().getSelectedItem().toString();
		String formaDePago = cbFormaPago.getSelectionModel().getSelectedItem().toString();
		IbInsurance datosSeguro = getInsurance(this.seguro.getNumeroPoliza());
		ObservableList<IbCuotesInsure> obsCuotesInsure = tbCuotes.getItems();
		List<IbCuotesInsure> listCuotesInsure = obsCuotesInsure;
		EntityManagerFactory emf;
		EntityManager em;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();

		insuOfficialCopy = datosSeguro;
		if (!formaDePago.isEmpty()) {
			IbMasterValue imv = util.masterValueUtil.getMasterValueByValorAndTipo(formaDePago,
					MasterTypes.TYPE_FORMA_PAGO);
			formaDePago = imv.getValor();
		}

		if (!cbDuracion.getSelectionModel().getSelectedItem().toString().isEmpty()) {
			IbMasterValue imv = util.masterValueUtil.getMasterValueByValorAndTipo(duracion, MasterTypes.TYPE_DURACION);
			duracion = imv.getValor();
		}

		/*
		 * 1º Si está bien la suma 2º si está bien la fecha inicio y fin
		 */
		if (isValidCuotes(event, dateIniVigor, dateFinVigor, duracion, formaDePago, obsCuotesInsure)) {
			// * 3º RETURN si hay cambios en duracion y forma de pago.
			// si no cambia quiere decir que es la misma cuota
			// si cambia la duracion o la forma de pago quiere decir que son
			// distintas cuotas

			// Extraemos de base de datos las cuotas que tiene el seguro.
			IbCuotesInsure ciOfficial = new IbCuotesInsure();
			TypedQuery<IbCuotesInsure> queryCuotes = em.createNamedQuery("IbCuotesInsure.findCoutesByInsure",
					IbCuotesInsure.class);
			queryCuotes.setParameter("seguro", this.seguro);
			List<IbCuotesInsure> listOfficialCuotes = queryCuotes.getResultList();
			if (!cambiaDuracionFP(formaDePago, duracion, event, insuOfficialCopy)) {
				// * 3ºA Comprobar que haya algun cambio en los datos del seguro
				// y en sus cuotas y hacer merge
				// recorremos todas las cuotas que estan en la
				// tabla nueva
				// ACTUALIZAMOS LA ENTIDAD SEGURO
				datosSeguro = actualizarSeguro(datosSeguro, duracion, formaDePago,MasterTypes.DESCRIPTION_ESTADO_VIGENTE);
				em.getTransaction().begin();
				em.merge(datosSeguro);
				em.getTransaction().commit();
				for (int i = 0; i < listCuotesInsure.size(); i++) {
					// recorremos todas las cuotas oficiales
					// comparando por la orden para saber si son
					// iguales

					ci = listCuotesInsure.get(i);
					for (int j = 0; j < listOfficialCuotes.size(); j++) {
						ciOfficial = listOfficialCuotes.get(j);
						// si son iguales actualizamos la cuota
						if (ci.getNumOrden() == ciOfficial.getNumOrden()) {
							// insertamos el id oficial para que a
							// la hora de hacer el merge
							// reconozca cual es.
							em.getTransaction().begin();
							ci.setIdibCuotesInsure(ciOfficial.getIdibCuotesInsure());
							ci.setIbInsurance(datosSeguro);
							em.merge(ci);
							em.getTransaction().commit();
						}
					}

				}
				messageInfo = "Se ha actualizado el seguro con la información establecida en las cuotas.";

			} else {
				// * 3ºB Comprobar si tiene alguna cuota pagada
				if (!cuotaConPagosRealizados()) {
					// * 3ºBA Guardar cambios del seguro y sus cuotas.
					// borrar cuotas
					datosSeguro = actualizarSeguro(datosSeguro, duracion, formaDePago,MasterTypes.DESCRIPTION_ESTADO_VIGENTE);
					em.getTransaction().begin();
					em.merge(datosSeguro);
					em.getTransaction().commit();
					for (int i = 0; i < listOfficialCuotes.size(); i++) {
						em.getTransaction().begin();
						ci = listOfficialCuotes.get(i);
						em.remove(ci);
						em.getTransaction().commit();
					}

					// añadimos nuevas cuotas
					for (int i = 0; i < listCuotesInsure.size(); i++) {
						em.getTransaction().begin();
						ci = listCuotesInsure.get(i);
						ci.setIbInsurance(insuOfficialCopy);
						em.persist(ci);
						em.getTransaction().commit();
						messageInfo = "Se han insertado las nuevas cuotas y se han eliminado las anteriores.";
					}
				} else {
					// * 3ºBB Mostrar error por que no puedes modificar cuotas
					// con una cuota dada de alta con pagos realizados.
					messageError = "No se puede actulizar las cuotas, ya que existen cuotas generadas originalmente con pagos efectuados.";
				}
			}

		} // si el mensaje no va vacío
		if (!messageInfo.isEmpty()) {
			Dialog dialog = new Dialog(DialogType.INFORMATION, "INFORMACIÓN", messageInfo);
			dialog.initModality(Modality.WINDOW_MODAL);
			dialog.initOwner(((Node) event.getSource()).getScene().getWindow());
			dialog.showAndWait();
		}
		if (!messageError.isEmpty()) {
			Dialog dialog = new Dialog(DialogType.ERROR, "ERROR", messageError);
			dialog.initModality(Modality.WINDOW_MODAL);
			dialog.initOwner(((Node) event.getSource()).getScene().getWindow());
			dialog.showAndWait();
		}

		// ESTADO FINALIZADO
		/*
		 * Realizamos las comprobaciones necesarias para ver si están todas las
		 * cuotas pagadas, si esto es así ponemos el estado del pago del seguro
		 * en finalizado.
		 */
		if(comprobarFinalizadoPagos()){
			Dialog dialog = new Dialog(DialogType.GENERIC_OK, "INFORMACIÓN", "Se procede a dar por finalizado el pago del seguro, ya que todas sus cuotas están pagadas.");
			dialog.initModality(Modality.WINDOW_MODAL);
			dialog.initOwner(((Node) event.getSource()).getScene().getWindow());
			dialog.showAndWait();
			actualizarSeguro(datosSeguro, duracion, formaDePago, MasterTypes.DESCRIPTION_ESTADO_FINALIZADO);
			em.getTransaction().begin();
			em.merge(datosSeguro);
			em.getTransaction().commit();
		}
		em.close();

	}

	private IbInsurance actualizarSeguro(IbInsurance datosSeguro, String duracion, String formaDePago, String estado) {
		// datosSeguro.setCompania(cbCompania.getSelectionModel().getSelectedItem().toString());
		LocalDate dateIniVigor = dpFechaEntradaVigor.getValue();
		LocalDate dateFinVigor = LocalDate.now(ZoneId.of(ZoneId.systemDefault().toString()));

		Date utilDateInicio = Date.from(dpFechaInicio.getValue().atStartOfDay(ZoneId.systemDefault()).toInstant());
		Date utilDateFin = Date.from(dpFechaFin.getValue().atStartOfDay(ZoneId.systemDefault()).toInstant());
		Date utilDateFechaEntradaVigor = Date
				.from(dpFechaEntradaVigor.getValue().atStartOfDay(ZoneId.systemDefault()).toInstant());
		datosSeguro.setFechaInicio(utilDateInicio);
		datosSeguro.setFechaFin(utilDateFin);
		datosSeguro.setFechaEntradaVigor(utilDateFechaEntradaVigor);

		switch (cbDuracion.getSelectionModel().getSelectedItem().toString()) {
		case "ANUAL":
			dateFinVigor = dateIniVigor.plusYears(1);
			break;
		case "SEMESTRAL":
			dateFinVigor = dateIniVigor.plusMonths(6);
			break;
		case "TRIMESTRAL":
			dateFinVigor = dateIniVigor.plusMonths(3);
			break;
		case "MENSUAL":
			dateFinVigor = dateIniVigor.plusMonths(1);
			break;
		default:
			break;
		}

		datosSeguro.setFechaFinEntradaVigor(Date.from(dateFinVigor.atStartOfDay(ZoneId.systemDefault()).toInstant()));
		double primaNeta = 0;

		primaNeta = Double.parseDouble(tvPrimaNeta.getText().replace(",", "."));

		datosSeguro.setPrimaNeta(primaNeta);

		datosSeguro.setDuracion(duracion);

		datosSeguro.setFormaPago(formaDePago);

		// INEST01-->Vigente
		datosSeguro.setEstado(estado);

		return datosSeguro;
	}

	private boolean cuotaConPagosRealizados() {
		// saber si tiene cuotas anteriores pagadas.
		boolean cuotaConPagosRealizados = false;
		EntityManagerFactory emf;
		EntityManager em;
		Byte pagado = 1;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();
		TypedQuery<IbCuotesInsure> query = em.createNamedQuery("IbCuotesInsure.findPayCoutes", IbCuotesInsure.class);
		query.setParameter("seguro", this.seguro);
		query.setParameter("pagado", pagado);
		List<IbCuotesInsure> listCuotesPagadas = query.getResultList();

		if (listCuotesPagadas.size() > 0) {
			cuotaConPagosRealizados = true;
		}
		em.close();
		return cuotaConPagosRealizados;
	}

	private boolean comprobarFinalizadoPagos() {
		// saber si tiene cuotas anteriores pagadas.
		boolean cuotaConPagosRealizados = false;
		EntityManagerFactory emf;
		EntityManager em;
		Byte pagado = 1;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();
		TypedQuery<IbCuotesInsure> query = em.createNamedQuery("IbCuotesInsure.findPayCoutes", IbCuotesInsure.class);
		query.setParameter("seguro", this.seguro);
		query.setParameter("pagado", pagado);
		List<IbCuotesInsure> listCuotesPagadas = query.getResultList();

		if (listCuotesPagadas.size() == tbCuotes.getItems().size()) {
			cuotaConPagosRealizados = true;
		}

		em.close();
		return cuotaConPagosRealizados;
	}

	private boolean isValidCuotes(Event event, LocalDate dateIniVigor, LocalDate dateFinVigor, String duracion,
			String formaDePago, ObservableList<IbCuotesInsure> obsCuotesInsure) {
		IbInsurance insuOfficialCopy = new IbInsurance();
		boolean isValid = false;
		String messageError = "";

		// saber si tiene cuotas anteriores pagadas.
		// fin saber si tiene cuotas ya pagadas

		// la suma del total no corresponde con el total
		if (DateUtil.isNumeric(tvPrimaNeta.getText())) {
			// saber si tiene algún campo sin rellenar
			if (cbDuracion.getSelectionModel().getSelectedItem() != null
					&& cbFormaPago.getSelectionModel().getSelectedItem() != null && !tvPrimaNeta.getText().isEmpty()) {
				// comprobar que la prima neta sea igual a todas las cuotas
				if (algoNumber.comprobarTotal(Double.parseDouble(tvPrimaNeta.getText()), obsCuotesInsure)) {

					// comprobar que la fecha inicio y fecha fin de pago
					// correspondan con las de los textFields de la pantalla
					if (algoNumber.comprobarFechas(dpFechaInicio.getValue(), dpFechaFin.getValue(), obsCuotesInsure,
							cbFormaPago.getSelectionModel().getSelectedItem().toString())) {
						isValid = true;

					} else {
						messageError = "La fecha inicio y fin no correspondan a las indicadas en los parámetros de entrada.\n";
					}
				} else {
					messageError = "Las sumas parciales de las cuotas no son iguales al total de la poliza.\n";
				}
			} else {
				messageError = "Existe algún campo que no está completo. Revísalos y vuelve a hacer click en aceptar cambios.\n";
			}
		} else {
			messageError = "La prima neta no es un valor numérico\n";
		}

		// si el mensaje no va vacío
		if (!messageError.isEmpty()) {
			Dialog dialog = new Dialog(DialogType.ERROR, "INFORMACIÓN", messageError);
			dialog.initModality(Modality.WINDOW_MODAL);
			dialog.initOwner(((Node) event.getSource()).getScene().getWindow());
			dialog.showAndWait();
		}
		return isValid;
	}

	@FXML
	public void handleDeshacerCambios(ActionEvent event) {
		initData(getInsurance(this.seguro.getNumeroPoliza()), getCustomer(this.cliente.getDniCif()), true);
	}

	private boolean cambiaDuracionFP(String formaDePago, String duracion, Event event, IbInsurance seguro) {
		boolean change = false;
		if (!seguro.getFormaPago().equals(formaDePago)
				|| (seguro.getFormaPago().equals(formaDePago) && !seguro.getDuracion().equals(duracion))) {
			seguro.setFormaPago(formaDePago);
			seguro.setDuracion(duracion);
			change = true;
		}

		return change;
	}

	private boolean comprobarComboBoxes() {
		boolean actualizar = true;
		if (null == cbFormaPago.getSelectionModel().getSelectedItem()
				|| null == cbDuracion.getSelectionModel().getSelectedItem()) {
			actualizar = false;
		}
		return actualizar;
	}

	private IbInsurance getInsurance(String numeroPoliza) {
		EntityManagerFactory emf;
		EntityManager em;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();
		TypedQuery<IbInsurance> query = em.createNamedQuery("IbInsurance.findByPoliza", IbInsurance.class);
		query.setParameter("poliza", numeroPoliza);
		List<IbInsurance> listInsurance = query.getResultList();
		IbInsurance insurance = null;
		if (listInsurance.size() > 0) {
			insurance = listInsurance.get(0);
		}
		em.close();
		return insurance;
	}

	private IbCustomer getCustomer(String dni) {
		// TODO Auto-generated method stub
		EntityManagerFactory emf;
		EntityManager em;
		emf = Persistence.createEntityManagerFactory("prodiSegur");
		em = emf.createEntityManager();
		EntityTransaction tx = em.getTransaction();
		TypedQuery<IbCustomer> query = em.createNamedQuery("IbCustomer.findDNI", IbCustomer.class);
		query.setParameter("dni", dni);
		List<IbCustomer> listCustomer = query.getResultList();
		IbCustomer cus = null;
		if (listCustomer.size() > 0) {
			cus = listCustomer.get(0);
		}
		return cus;
	}
}
