package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.Tab;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

public class InsuranceManagementMenuOverviewController {
	@FXML
	private Tab tabDatosSeguro;
	@FXML
	private Label lbTitular;
	@FXML
	private Label lbPoliza;
	@FXML
	private ComboBox cbTipoRiesgo;
	@FXML
	private TextField tfComision;
	@FXML
	private TextField tfLiquidez;
	@FXML
	private ComboBox cbCompania;
	@FXML
	private ComboBox cbEstado;
	@FXML
	private Tab tabDetalleSeguro;
	@FXML
	private TextField tfMarca;
	@FXML
	private TextField tfModelo;
	@FXML
	private TextField tfMatricula;
	@FXML
	private TextField tfCaballos;
	@FXML
	private TextField tfCilindrada;
	@FXML
	private TextField tfPMA;
	@FXML
	private TextField tfRemolque;
	@FXML
	private TextField tfAccesorios;
	@FXML
	private DatePicker dpFechaMatricula;
	@FXML
	private CheckBox chkPublico;
	@FXML
	private ComboBox cbCobertura;
	@FXML
	private ComboBox cbVehiculo;
	@FXML
	private Button btnAnadirTipoVehiculo;
	@FXML
	private Button btnAnadirCobertura;
	@FXML
	private Button btActualizar;
	@FXML
	private Button handleBorrar;

	// Event Listener on Button[#btnAnadirTipoVehiculo].onAction
	@FXML
	public void handleAnadirTipVehiculo(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAnadirCobertura].onAction
	@FXML
	public void handleAnadirCobertura(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btActualizar].onAction
	@FXML
	public void handleActualizar(ActionEvent event) {
		// TODO Autogenerated
	}
}
