package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class PersonManagementOverviewController {
	@FXML
	private TableView personTable;
	@FXML
	private TableColumn firstNameColumn;
	@FXML
	private TableColumn lastNameColumn;
	@FXML
	private TextField filterField;
	@FXML
	private Label firstNameLabel;
	@FXML
	private Label lastNameLabel;
	@FXML
	private Label streetLabel;
	@FXML
	private Label postalCodeLabel;
	@FXML
	private Label birthdayLabel;
	@FXML
	private Label cityLabel;
	@FXML
	private Label DNILabel;
	@FXML
	private Button btNuevo;
	@FXML
	private Button btEditar;
	@FXML
	private Button btBorrar;
	@FXML
	private Button btSiguiente;
	@FXML
	private CheckBox cbTitular;
	@FXML
	private CheckBox cbConductor;
	@FXML
	private CheckBox cbTomador;
	@FXML
	private TableView personRelationTable;
	@FXML
	private TableColumn nombreRelationColumn;
	@FXML
	private TableColumn apellidosRelationColumn;
	@FXML
	private TableColumn dniRelationColumn;
	@FXML
	private TableColumn tipoRelationColumn;
	@FXML
	private Button btAnadir;
	@FXML
	private Button btBorrarRelation;

	
	@FXML
	public void handleBucar(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btNuevo].onAction
	@FXML
	public void handleNewPerson(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btEditar].onAction
	@FXML
	public void handleEditPerson(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btBorrar].onAction
	@FXML
	public void handleDeletePerson(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btSiguiente].onAction
	@FXML
	public void handleSiguiente(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btAnadir].onAction
	@FXML
	public void handleAnadir(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btBorrarRelation].onAction
	@FXML
	public void handleBorrar(ActionEvent event) {
		// TODO Autogenerated
	}
}
